[package]
name = "handlers"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
service = { path = "../service" }
common = { path = "../common" }

axum = { workspace = true }